name: Family Biz
favicon: null
layout_spectrum: 0.6955720169935375
typography_spectrum: 0.31475744023919106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.008408854715526104
  lightness: 0.6755060739815235
  saturation: 0.1110455843154341
  rhythmicContrast: 0.20474038529209793
purpose: []
